name: hasura
on:
  push:
    paths:
      - 'packages/hasura/**'
      - '.github/workflows/hasura.yaml'
jobs:
  install-hasura-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -L https://github.com/hasura/graphql-engine/raw/master/cli/get.sh | bash
      - run: hasura -v
