name: services
on:
  push:
    paths:
      - 'packages/services/**'
      - '.github/workflows/services.yaml'
jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
